"""initial migration

Revision ID: 01cff2b0f8fe
Revises: 
Create Date: 2026-03-13 15:10:51.925502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01cff2b0f8fe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=255), nullable=True),
    sa.Column('bin', sa.String(length=12), nullable=False),
    sa.Column('legal_address', sa.String(length=255), nullable=False),
    sa.Column('actual_address', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('contact_position', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('company_status', sa.Enum('active', 'inactive', 'blocked', 'archived', name='company_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bin')
    )
    op.create_index(op.f('ix_companies_company_status'), 'companies', ['company_status'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_table('countries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('company_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('bank_name', sa.String(length=255), nullable=False),
    sa.Column('bank_bik', sa.String(length=20), nullable=False),
    sa.Column('bank_account', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.Enum('KZT', 'USD', 'RUB', 'EUR', name='currency_enum'), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('swift', sa.String(length=20), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'bank_account', 'currency', name='uq_company_account')
    )
    op.create_index(op.f('ix_company_accounts_company_id'), 'company_accounts', ['company_id'], unique=False)
    op.create_table('company_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('customer', 'payer', 'carrier', 'partner', 'supplier', name='company_role_list_enum'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'role', name='uq_company_role')
    )
    op.create_index(op.f('ix_company_roles_company_id'), 'company_roles', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_roles_role'), 'company_roles', ['role'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('middle_name', sa.String(length=255), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='gender_enum'), nullable=False),
    sa.Column('id_number', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('job_position', sa.Enum('director', 'ceo', 'accountant', 'dispatcher', 'logistician', 'manager', 'hr_manager', 'head', 'mechanic', 'driver', name='job_position_enum'), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('marital_status', sa.Enum('single', 'married', 'divorced', 'widowed', name='marital_status_enum'), nullable=True),
    sa.Column('status', sa.Enum('internship', 'probation', 'active', 'vacation', 'sick_leave', 'dismissed', name='employee_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id_number')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('vehicle_type', sa.Enum('truck_tractor', 'semi_trailer', 'tow_truck', 'trailer', 'car', 'van', name='vehicle_type_enum'), nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('sts_number', sa.String(length=20), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('required_license_category', sa.Enum('a1', 'a', 'b1', 'b', 'c1', 'c', 'd1', 'd', 'be', 'c1e', 'ce', 'd1e', 'de', name='required_license_category_enum'), nullable=False),
    sa.Column('vehicle_category', sa.Enum('m1', 'm2', 'm3', 'n1', 'n2', 'n3', 'o1', 'o2', 'o3', name='vehicle_category_enum'), nullable=False),
    sa.Column('engine_volume_cc', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('unladen_weight_kg', sa.Integer(), nullable=False),
    sa.Column('gross_weight_kg', sa.Integer(), nullable=False),
    sa.Column('registered_owner_name', sa.String(length=255), nullable=False),
    sa.Column('special_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='vehicle_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.CheckConstraint('gross_weight_kg > 0', name='ck_vehicle_gross_weight_positive'),
    sa.CheckConstraint('unladen_weight_kg > 0', name='ck_vehicle_unladen_weight_positive'),
    sa.CheckConstraint('year > 1900', name='ck_vehicle_year_positive'),
    sa.ForeignKeyConstraint(['owner_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plate_number'),
    sa.UniqueConstraint('sts_number'),
    sa.UniqueConstraint('vin')
    )
    op.create_index(op.f('ix_vehicles_owner_id'), 'vehicles', ['owner_id'], unique=False)
    op.create_table('city_distances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('city1_id', sa.UUID(), nullable=False),
    sa.Column('city2_id', sa.UUID(), nullable=False),
    sa.Column('distance_km', sa.Integer(), nullable=False),
    sa.CheckConstraint('city1_id <> city2_id', name='ck_city_distance_not_same_city'),
    sa.CheckConstraint('distance_km > 0', name='ck_city_distance_positive'),
    sa.ForeignKeyConstraint(['city1_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['city2_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city1_id', 'city2_id', name='uq_city_distance')
    )
    op.create_table('drivers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_table('locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location_type', sa.Enum('plant', 'warehouse', 'dealer', 'parking', 'service', 'other', name='location_type_enum'), nullable=False),
    sa.Column('location_type_custom', sa.Text(), nullable=True),
    sa.Column('address_line', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'city_id', name='uq_location_name_city')
    )
    op.create_index(op.f('ix_locations_city_id'), 'locations', ['city_id'], unique=False)
    op.create_index(op.f('ix_locations_company_id'), 'locations', ['company_id'], unique=False)
    op.add_column('cities', sa.Column('country_id', sa.UUID(), nullable=False))
    op.alter_column('cities', 'name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('cities', 'region',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_city_region_country'), 'cities', type_='unique')
    op.create_index(op.f('ix_cities_country_id'), 'cities', ['country_id'], unique=False)
    op.create_index(op.f('ix_cities_name'), 'cities', ['name'], unique=False)
    op.create_unique_constraint('uq_name_region_country', 'cities', ['name', 'region', 'country_id'])
    op.create_foreign_key(None, 'cities', 'countries', ['country_id'], ['id'])
    op.drop_column('cities', 'country')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('country', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cities', type_='foreignkey')
    op.drop_constraint('uq_name_region_country', 'cities', type_='unique')
    op.drop_index(op.f('ix_cities_name'), table_name='cities')
    op.drop_index(op.f('ix_cities_country_id'), table_name='cities')
    op.create_unique_constraint(op.f('uq_city_region_country'), 'cities', ['name', 'region', 'country'], postgresql_nulls_not_distinct=False)
    op.alter_column('cities', 'region',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('cities', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('cities', 'country_id')
    op.drop_index(op.f('ix_locations_company_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_city_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_table('drivers')
    op.drop_table('city_distances')
    op.drop_index(op.f('ix_vehicles_owner_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_table('employees')
    op.drop_index(op.f('ix_company_roles_role'), table_name='company_roles')
    op.drop_index(op.f('ix_company_roles_company_id'), table_name='company_roles')
    op.drop_table('company_roles')
    op.drop_index(op.f('ix_company_accounts_company_id'), table_name='company_accounts')
    op.drop_table('company_accounts')
    op.drop_table('countries')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_company_status'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
